#ifndef MDIO_CONFIG_H_
#define MDIO_CONFIG_H_

#define DIO_U8_PA0_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA1_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA2_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA3_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA3_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA4_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA5_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA6_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA7_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA8_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA9_MODE    MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA10_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA11_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA12_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA13_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA14_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PA15_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB0_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB1_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB2_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB3_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB4_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB5_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB6_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB7_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB8_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB9_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB10_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB11_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB12_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB13_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB14_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PB15_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PC13_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PC14_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2
#define DIO_U8_PC15_MODE   MDIO_MODE_OUTPUT_PUSHPULL_2

#endif
